# This file was generated by GoReleaser. DO NOT EDIT.
cask "momapeer" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "b3441de7281fa662264dfe7134374b870c595137d0b9b8c71a2f958af11faada"
      url "https://github.com/zzycxz/momapeer/releases/download/v#{version}/momapeer-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "bce2c18317d2b1b8d1b66e4b5981384ed059b3704e2498356760080506e433b7"
      url "https://github.com/zzycxz/momapeer/releases/download/v#{version}/momapeer-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3cbdc13416fd8f774742411e069ce06d105e7c8134c7925a5f5e24a73cdc7ea7"
      url "https://github.com/zzycxz/momapeer/releases/download/v#{version}/momapeer-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "5fad60ead12ab75b417842f19d204ea1abff150be65343852cb6715a912b09b8"
      url "https://github.com/zzycxz/momapeer/releases/download/v#{version}/momapeer-linux-arm64.tar.gz"
    end
  end

  name "momapeer"
  desc "A MoMA (---) AI coding agent for the terminal."
  homepage "https://github.com/zzycxz/momapeer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "momapeer"

  postflight do
    if OS.mac?

      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/momapeer"]

    end
  end

  # No zap stanza required

end
