# This file was generated by GoReleaser. DO NOT EDIT.
cask "momapeer" do
  version "0.1.8"

  on_macos do
    on_intel do
      sha256 "5a3cebc2fafa48e214347dd87d0dfd3a36ba12149b5f337968ca76a21c1103cb"
      url "https://github.com/zzycxz/momapeer/releases/download/v#{version}/momapeer-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "b218258e55549f1c3542be9bc08cb97a516cd8ee88b315a063a6071cf2dd1527"
      url "https://github.com/zzycxz/momapeer/releases/download/v#{version}/momapeer-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "65b1efeb056cec4344675c200c5bcb43542cc4db7d85acc4b4ec9cbb60868136"
      url "https://github.com/zzycxz/momapeer/releases/download/v#{version}/momapeer-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "976a31ccc319cf33ed2d5af3218de2967fa2ad50e034aca7a8be9437d8fec8bc"
      url "https://github.com/zzycxz/momapeer/releases/download/v#{version}/momapeer-linux-arm64.tar.gz"
    end
  end

  name "momapeer"
  desc "A MoMA (九天) AI coding agent for the terminal."
  homepage "https://github.com/zzycxz/momapeer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "momapeer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/momapeer"]
    end
  end

  # No zap stanza required

end
