# This file was generated by GoReleaser. DO NOT EDIT.
cask "momapeer" do
  version "0.1.8"

  on_macos do
    on_intel do
      sha256 "c09d83f7ff783bc251d192cf6dc3d6b6fe397aebe58a7ab77925fb75119e7146"
      url "https://github.com/zzycxz/momapeer/releases/download/v#{version}/momapeer-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "dc1ddfff887dfdc6cab3fd33da53c3c3b47c698c91b0ae49560361803d56eedc"
      url "https://github.com/zzycxz/momapeer/releases/download/v#{version}/momapeer-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9269e4c61d9ab773e082f19a85fea233c24605b67bef0195ea09d185ca44e5e8"
      url "https://github.com/zzycxz/momapeer/releases/download/v#{version}/momapeer-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "9b46eada620718d2df1d7a5c644ba45c72ad4abda1620aa128f7b65fda46eb05"
      url "https://github.com/zzycxz/momapeer/releases/download/v#{version}/momapeer-linux-arm64.tar.gz"
    end
  end

  name "momapeer"
  desc "A MoMA (九天) AI coding agent for the terminal."
  homepage "https://github.com/zzycxz/momapeer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "momapeer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/momapeer"]
    end
  end

  # No zap stanza required

end
